### ISSUE TITLE
Release text should be more complete

### ISSUE THREAD

**Issue by cclauss** [zrzka/blackmamba#18]
The text that goes into https://forum.omz-software.com/topic/4303/black-mamba-releases should __also__ go into https://github.com/zrzka/blackmamba/releases

**Comment by zrzka** [comment]
Yup, will do it retrospectively as well. I'll change the way how I do it ...

* CHANGELOG.rst -> CHANGELOG.md (easier copy & paste)
* CHANGELOG.md -> release notes (here on GH)
* Link to the GH release -> forum

**Comment by zrzka** [comment]
Done. Markdown changelog, releases updated with release info back to 0.0.11. Future releases will contain description and I'll post link to the forum only.
