### ISSUE TITLE
Page Up / Page Down Support

### ISSUE THREAD

**Issue by wolf71** [zrzka/blackmamba#19]
Hope can add Cmd+up/Cmd+down to Page Up / Page Down.

**Comment by zrzka** [comment]
Released in 0.0.25. But I did use Ctrl Up & Down. Cmd Up & Down is used for start / end. Also check [this bug](https://github.com/omz/Pythonista-Issues/issues/395). It means, that to be safe, just hit left / right arrow key after ctrl up & down, so, it doesn't scroll back.
