### ISSUE TITLE
Closing console after startup?

### ISSUE THREAD

**Issue by GiacomoLaw** [zrzka/blackmamba#22]
Is it possible to close the console after BM has started?

I'd also like to say thanks for this absolutely amazing project - really helps me, thanks so much!

**Comment by zrzka** [comment]
I don't think it makes much sense to add something like this into the Black Mamba. Although, you can do it even now ...

**Disable logs**

Check [pythonista_startup.py](https://github.com/zrzka/blackmamba/blob/master/pythonista_startup.py) example.

```python
import blackmamba
import blackmamba.log as log

log.set_level(log.ERROR)
blackmamba.main()
```

Log level `INFO` is changed to `ERROR` and you'll see only red errors -> console will not appear during Black Mamba startup.

**Hide it**

Preferred way is this one. Just hide yourself in the `pythonista_startup.py`. Place it after `blackmamba.main()` call.

```python
import blackmamba
import console

blackmamba.main()
console.hide_output()
```

Thanks for your support :)

**Comment by GiacomoLaw** [comment]
Awesome, the second one works perfectly! Didn't know you could do that.

Thanks so much!
