### ISSUE TITLE
Drag & Drop: Automatically update after dropping

### ISSUE THREAD

**Issue by iven00000000** [zrzka/blackmamba#26]
I found that after dropping something from working copy, the pop window that shows the folders tree did not update. I have to restart the script to make the content of the pop window renew. Hope there will be a mechanism to automatically update the directories tree after drop anything into pythonista.

**Comment by zrzka** [comment]
It’s documented here http://blackmamba.readthedocs.io/en/stable/user/scripts.html#module-blackmamba.script.drag_and_drop and it will be added.

**Comment by iven00000000** [comment]
Sorry, I didn't noticed that. Thank you.

**Comment by zrzka** [comment]
Keep it open, it’s valid issue even if it’s documented :)

**Comment by zrzka** [comment]
Fixed in 1.2.1 (will be released later today).

**Comment by zrzka** [comment]
@iven00000000 1.2.1 with fix just released.
