### ISSUE TITLE
Many Actions Lauchining Pythonista 2

### ISSUE THREAD

**Issue by Phuket2** [zrzka/blackmamba#29]
@zrzka, I guess you dont have Pythonista 2.7 app installed on your device.  But I have both. When I try to use quick open, toggle comment, Action Quickly etc...Pythonista 2.7 is launched.

So the below image is from what happens if I invoke toggle comments.  Pythonista v2.7 ( I think its called that in the app store) opens and you can see the bm msg.

BM v1.3.0

![](https://dl.dropbox.com/s/2bpa4sqsuvd003k/File%2019-10-17%2C%2017%2042%2057.png?dl=1)

**Comment by zrzka** [comment]
@Phuket2 does this help?

https://github.com/zrzka/blackmamba/releases/tag/v1.3.1

**Comment by Phuket2** [comment]
@zrzka , yes its all working again. Thanks for the quick update!

**Comment by zrzka** [comment]
@Phuket2 glad it fixes it :)
