### ISSUE TITLE
Update Version msg could use a tweak

### ISSUE THREAD

**Issue by Phuket2** [zrzka/blackmamba#31]
@zrzka, when you run the requests console line install, Its not clear what version you are upgrading from. Unless you have run it a few times before its a bit confusing. I put a screen shot below.  Its not a big deal, but guessing easy to fix. Its been like this for a while.
I just checked again. I thought it was a different msg if you did not already have the latest version installed. But it appears both suituations (running the cmd with an earlier version of BM installed or the latest version installed) Generate the same message. 
The below image, was taken when I was upgrading from 1.3.1

![](https://dl.dropbox.com/s/i8d47q04wsoe9lz/File%2025-10-17%2C%2015%2013%2013.png?dl=1)

**Comment by zrzka** [comment]
Fixed.
