### ISSUE TITLE
Install idea

### ISSUE THREAD

**Issue by Phuket2** [zrzka/blackmamba#32]
@zrzka, stupidly before each time I wanted to upgrade BM, I would have to go searching for the install cmd.  It was not so bad when it was in the git, but then it moved to the docs.  
So finally I did the sane thing and made a file at the root of Documents just called bm_update.py with the install cmd "import requests as r; exec(r.get('http://bit.ly/get-blackmamba').text)" inside.  
Yeah, I know it does not take a genius to figure out you should do something like that.  

But maybe its something you might want your installer to do, create an update file that is.  StaSh installs a 'launch_stash.py' into the root of Documents. So its not unprecedented.  

Given the slightly unusual nature of Pythonista, it would seem to me that a Std Dir called something like User_Install_Scripts or something like that could be used for apps to create a directory inside of named same as there app where they could place Install scripts, maybe some other non critical information/config about their Apps.  I realise this is an @omz thing.  But just a thought.

**Comment by zrzka** [comment]
I'm not going to clutter `~/Documents` folder. Here's what I did.

**New update dialog**

![d766f61b-f740-4c0b-94a7-9d51dad7fee9](https://user-images.githubusercontent.com/1084172/32099060-15035264-bb0f-11e7-8861-72b78b0b7a69.jpeg)

**Cancel tapped**

![4a9eaa76-25ff-4817-b6e8-1351f6153bc6](https://user-images.githubusercontent.com/1084172/32099089-31484d08-bb0f-11e7-889a-fb945a129165.jpeg)

**Update tapped**

`site-packages-3/blackmamba/script/selfupdate.py` is executed.

**Another way**

You can add `site-packages-3/blackmamba/script/selfupdate.py` as an action item (wrench) as well.

**Note**

Not yet released. And when this will be released, you'll have to update via the old way. You'll be able to experience this behavior in subsequent releases.
